export const EMAIL_MESSAGE_REPOSITORY = 'EMAIL_MESSAGE_REPOSITORY';
export const EMAIL_SUBJECT_REPOSITORY = 'EMAIL_SUBJECT_REPOSITORY';
export const EMAIL_MESSAGE_TS_REPOSITORY = 'EMAIL_MESSAGE_TS_REPOSITORY';
