export const NETFLIX_SIGNIN_OTP = 'NETFLIX_SIGNIN_OTP';
export const NETFLIX_REQ_RESET_PASSWORD = 'NETFLIX_REQ_RESET_PASSWORD';
export const NETFLIX_TRAVEL_OTP = 'NETFLIX_TRAVEL_OTP';
export const NETFLIX_HOUSE_CHANGE = 'NETFLIX_HOUSE_CHANGE';
export const NETFLIX_VERIFY_EMAIL = 'NETFLIX_VERIFY_EMAIL';
export const NETFLIX_CANCELLATION = 'NETFLIX_CANCELLATION';
