/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardVoucherGeneratorIndexRouteImport } from './routes/dashboard/voucher-generator/index'
import { Route as DashboardTransactionIndexRouteImport } from './routes/dashboard/transaction/index'
import { Route as DashboardSettingIndexRouteImport } from './routes/dashboard/setting/index'
import { Route as DashboardProductIndexRouteImport } from './routes/dashboard/product/index'
import { Route as DashboardPlatformProductIndexRouteImport } from './routes/dashboard/platform-product/index'
import { Route as DashboardEmailIndexRouteImport } from './routes/dashboard/email/index'
import { Route as DashboardEmailMessageIndexRouteImport } from './routes/dashboard/email-message/index'
import { Route as DashboardAccountIndexRouteImport } from './routes/dashboard/account/index'
import { Route as DashboardTransactionCreateRouteImport } from './routes/dashboard/transaction/create'
import { Route as DashboardProductCreateRouteImport } from './routes/dashboard/product/create'
import { Route as DashboardPlatformProductCreateRouteImport } from './routes/dashboard/platform-product/create'
import { Route as DashboardPlatformProductIdRouteImport } from './routes/dashboard/platform-product/$id'
import { Route as DashboardEmailCreateRouteImport } from './routes/dashboard/email/create'
import { Route as DashboardEmailIdRouteImport } from './routes/dashboard/email/$id'
import { Route as DashboardAccountCreateRouteImport } from './routes/dashboard/account/create'
import { Route as DashboardAccountSlugRouteImport } from './routes/dashboard/account/$slug'
import { Route as DashboardSettingTutorialIndexRouteImport } from './routes/dashboard/setting/tutorial.index'
import { Route as DashboardSettingLandingIndexRouteImport } from './routes/dashboard/setting/landing.index'
import { Route as DashboardSettingArticleIndexRouteImport } from './routes/dashboard/setting/article.index'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardVoucherGeneratorIndexRoute =
  DashboardVoucherGeneratorIndexRouteImport.update({
    id: '/voucher-generator/',
    path: '/voucher-generator/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTransactionIndexRoute =
  DashboardTransactionIndexRouteImport.update({
    id: '/transaction/',
    path: '/transaction/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingIndexRoute = DashboardSettingIndexRouteImport.update({
  id: '/setting/',
  path: '/setting/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductIndexRoute = DashboardProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlatformProductIndexRoute =
  DashboardPlatformProductIndexRouteImport.update({
    id: '/platform-product/',
    path: '/platform-product/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailIndexRoute = DashboardEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailMessageIndexRoute =
  DashboardEmailMessageIndexRouteImport.update({
    id: '/email-message/',
    path: '/email-message/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionCreateRoute =
  DashboardTransactionCreateRouteImport.update({
    id: '/transaction/create',
    path: '/transaction/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductCreateRoute = DashboardProductCreateRouteImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlatformProductCreateRoute =
  DashboardPlatformProductCreateRouteImport.update({
    id: '/platform-product/create',
    path: '/platform-product/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPlatformProductIdRoute =
  DashboardPlatformProductIdRouteImport.update({
    id: '/platform-product/$id',
    path: '/platform-product/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailCreateRoute = DashboardEmailCreateRouteImport.update({
  id: '/email/create',
  path: '/email/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailIdRoute = DashboardEmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountCreateRoute = DashboardAccountCreateRouteImport.update({
  id: '/account/create',
  path: '/account/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountSlugRoute = DashboardAccountSlugRouteImport.update({
  id: '/account/$slug',
  path: '/account/$slug',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingTutorialIndexRoute =
  DashboardSettingTutorialIndexRouteImport.update({
    id: '/setting/tutorial/',
    path: '/setting/tutorial/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingLandingIndexRoute =
  DashboardSettingLandingIndexRouteImport.update({
    id: '/setting/landing/',
    path: '/setting/landing/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingArticleIndexRoute =
  DashboardSettingArticleIndexRouteImport.update({
    id: '/setting/article/',
    path: '/setting/article/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/$slug': typeof DashboardAccountSlugRoute
  '/dashboard/account/create': typeof DashboardAccountCreateRoute
  '/dashboard/email/$id': typeof DashboardEmailIdRoute
  '/dashboard/email/create': typeof DashboardEmailCreateRoute
  '/dashboard/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/dashboard/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/dashboard/product/create': typeof DashboardProductCreateRoute
  '/dashboard/transaction/create': typeof DashboardTransactionCreateRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/dashboard/email-message': typeof DashboardEmailMessageIndexRoute
  '/dashboard/email': typeof DashboardEmailIndexRoute
  '/dashboard/platform-product': typeof DashboardPlatformProductIndexRoute
  '/dashboard/product': typeof DashboardProductIndexRoute
  '/dashboard/setting': typeof DashboardSettingIndexRoute
  '/dashboard/transaction': typeof DashboardTransactionIndexRoute
  '/dashboard/voucher-generator': typeof DashboardVoucherGeneratorIndexRoute
  '/dashboard/setting/article': typeof DashboardSettingArticleIndexRoute
  '/dashboard/setting/landing': typeof DashboardSettingLandingIndexRoute
  '/dashboard/setting/tutorial': typeof DashboardSettingTutorialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/account/$slug': typeof DashboardAccountSlugRoute
  '/dashboard/account/create': typeof DashboardAccountCreateRoute
  '/dashboard/email/$id': typeof DashboardEmailIdRoute
  '/dashboard/email/create': typeof DashboardEmailCreateRoute
  '/dashboard/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/dashboard/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/dashboard/product/create': typeof DashboardProductCreateRoute
  '/dashboard/transaction/create': typeof DashboardTransactionCreateRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/dashboard/email-message': typeof DashboardEmailMessageIndexRoute
  '/dashboard/email': typeof DashboardEmailIndexRoute
  '/dashboard/platform-product': typeof DashboardPlatformProductIndexRoute
  '/dashboard/product': typeof DashboardProductIndexRoute
  '/dashboard/setting': typeof DashboardSettingIndexRoute
  '/dashboard/transaction': typeof DashboardTransactionIndexRoute
  '/dashboard/voucher-generator': typeof DashboardVoucherGeneratorIndexRoute
  '/dashboard/setting/article': typeof DashboardSettingArticleIndexRoute
  '/dashboard/setting/landing': typeof DashboardSettingLandingIndexRoute
  '/dashboard/setting/tutorial': typeof DashboardSettingTutorialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/$slug': typeof DashboardAccountSlugRoute
  '/dashboard/account/create': typeof DashboardAccountCreateRoute
  '/dashboard/email/$id': typeof DashboardEmailIdRoute
  '/dashboard/email/create': typeof DashboardEmailCreateRoute
  '/dashboard/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/dashboard/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/dashboard/product/create': typeof DashboardProductCreateRoute
  '/dashboard/transaction/create': typeof DashboardTransactionCreateRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
  '/dashboard/email-message/': typeof DashboardEmailMessageIndexRoute
  '/dashboard/email/': typeof DashboardEmailIndexRoute
  '/dashboard/platform-product/': typeof DashboardPlatformProductIndexRoute
  '/dashboard/product/': typeof DashboardProductIndexRoute
  '/dashboard/setting/': typeof DashboardSettingIndexRoute
  '/dashboard/transaction/': typeof DashboardTransactionIndexRoute
  '/dashboard/voucher-generator/': typeof DashboardVoucherGeneratorIndexRoute
  '/dashboard/setting/article/': typeof DashboardSettingArticleIndexRoute
  '/dashboard/setting/landing/': typeof DashboardSettingLandingIndexRoute
  '/dashboard/setting/tutorial/': typeof DashboardSettingTutorialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/'
    | '/dashboard/account/$slug'
    | '/dashboard/account/create'
    | '/dashboard/email/$id'
    | '/dashboard/email/create'
    | '/dashboard/platform-product/$id'
    | '/dashboard/platform-product/create'
    | '/dashboard/product/create'
    | '/dashboard/transaction/create'
    | '/dashboard/account'
    | '/dashboard/email-message'
    | '/dashboard/email'
    | '/dashboard/platform-product'
    | '/dashboard/product'
    | '/dashboard/setting'
    | '/dashboard/transaction'
    | '/dashboard/voucher-generator'
    | '/dashboard/setting/article'
    | '/dashboard/setting/landing'
    | '/dashboard/setting/tutorial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/dashboard/account/$slug'
    | '/dashboard/account/create'
    | '/dashboard/email/$id'
    | '/dashboard/email/create'
    | '/dashboard/platform-product/$id'
    | '/dashboard/platform-product/create'
    | '/dashboard/product/create'
    | '/dashboard/transaction/create'
    | '/dashboard/account'
    | '/dashboard/email-message'
    | '/dashboard/email'
    | '/dashboard/platform-product'
    | '/dashboard/product'
    | '/dashboard/setting'
    | '/dashboard/transaction'
    | '/dashboard/voucher-generator'
    | '/dashboard/setting/article'
    | '/dashboard/setting/landing'
    | '/dashboard/setting/tutorial'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard/'
    | '/dashboard/account/$slug'
    | '/dashboard/account/create'
    | '/dashboard/email/$id'
    | '/dashboard/email/create'
    | '/dashboard/platform-product/$id'
    | '/dashboard/platform-product/create'
    | '/dashboard/product/create'
    | '/dashboard/transaction/create'
    | '/dashboard/account/'
    | '/dashboard/email-message/'
    | '/dashboard/email/'
    | '/dashboard/platform-product/'
    | '/dashboard/product/'
    | '/dashboard/setting/'
    | '/dashboard/transaction/'
    | '/dashboard/voucher-generator/'
    | '/dashboard/setting/article/'
    | '/dashboard/setting/landing/'
    | '/dashboard/setting/tutorial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/voucher-generator/': {
      id: '/dashboard/voucher-generator/'
      path: '/voucher-generator'
      fullPath: '/dashboard/voucher-generator'
      preLoaderRoute: typeof DashboardVoucherGeneratorIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transaction/': {
      id: '/dashboard/transaction/'
      path: '/transaction'
      fullPath: '/dashboard/transaction'
      preLoaderRoute: typeof DashboardTransactionIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setting/': {
      id: '/dashboard/setting/'
      path: '/setting'
      fullPath: '/dashboard/setting'
      preLoaderRoute: typeof DashboardSettingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product/': {
      id: '/dashboard/product/'
      path: '/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof DashboardProductIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/': {
      id: '/dashboard/platform-product/'
      path: '/platform-product'
      fullPath: '/dashboard/platform-product'
      preLoaderRoute: typeof DashboardPlatformProductIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/': {
      id: '/dashboard/email/'
      path: '/email'
      fullPath: '/dashboard/email'
      preLoaderRoute: typeof DashboardEmailIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email-message/': {
      id: '/dashboard/email-message/'
      path: '/email-message'
      fullPath: '/dashboard/email-message'
      preLoaderRoute: typeof DashboardEmailMessageIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/': {
      id: '/dashboard/account/'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transaction/create': {
      id: '/dashboard/transaction/create'
      path: '/transaction/create'
      fullPath: '/dashboard/transaction/create'
      preLoaderRoute: typeof DashboardTransactionCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product/create': {
      id: '/dashboard/product/create'
      path: '/product/create'
      fullPath: '/dashboard/product/create'
      preLoaderRoute: typeof DashboardProductCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/create': {
      id: '/dashboard/platform-product/create'
      path: '/platform-product/create'
      fullPath: '/dashboard/platform-product/create'
      preLoaderRoute: typeof DashboardPlatformProductCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/$id': {
      id: '/dashboard/platform-product/$id'
      path: '/platform-product/$id'
      fullPath: '/dashboard/platform-product/$id'
      preLoaderRoute: typeof DashboardPlatformProductIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/create': {
      id: '/dashboard/email/create'
      path: '/email/create'
      fullPath: '/dashboard/email/create'
      preLoaderRoute: typeof DashboardEmailCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/$id': {
      id: '/dashboard/email/$id'
      path: '/email/$id'
      fullPath: '/dashboard/email/$id'
      preLoaderRoute: typeof DashboardEmailIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/create': {
      id: '/dashboard/account/create'
      path: '/account/create'
      fullPath: '/dashboard/account/create'
      preLoaderRoute: typeof DashboardAccountCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/$slug': {
      id: '/dashboard/account/$slug'
      path: '/account/$slug'
      fullPath: '/dashboard/account/$slug'
      preLoaderRoute: typeof DashboardAccountSlugRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setting/tutorial/': {
      id: '/dashboard/setting/tutorial/'
      path: '/setting/tutorial'
      fullPath: '/dashboard/setting/tutorial'
      preLoaderRoute: typeof DashboardSettingTutorialIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setting/landing/': {
      id: '/dashboard/setting/landing/'
      path: '/setting/landing'
      fullPath: '/dashboard/setting/landing'
      preLoaderRoute: typeof DashboardSettingLandingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/setting/article/': {
      id: '/dashboard/setting/article/'
      path: '/setting/article'
      fullPath: '/dashboard/setting/article'
      preLoaderRoute: typeof DashboardSettingArticleIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountSlugRoute: typeof DashboardAccountSlugRoute
  DashboardAccountCreateRoute: typeof DashboardAccountCreateRoute
  DashboardEmailIdRoute: typeof DashboardEmailIdRoute
  DashboardEmailCreateRoute: typeof DashboardEmailCreateRoute
  DashboardPlatformProductIdRoute: typeof DashboardPlatformProductIdRoute
  DashboardPlatformProductCreateRoute: typeof DashboardPlatformProductCreateRoute
  DashboardProductCreateRoute: typeof DashboardProductCreateRoute
  DashboardTransactionCreateRoute: typeof DashboardTransactionCreateRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
  DashboardEmailMessageIndexRoute: typeof DashboardEmailMessageIndexRoute
  DashboardEmailIndexRoute: typeof DashboardEmailIndexRoute
  DashboardPlatformProductIndexRoute: typeof DashboardPlatformProductIndexRoute
  DashboardProductIndexRoute: typeof DashboardProductIndexRoute
  DashboardSettingIndexRoute: typeof DashboardSettingIndexRoute
  DashboardTransactionIndexRoute: typeof DashboardTransactionIndexRoute
  DashboardVoucherGeneratorIndexRoute: typeof DashboardVoucherGeneratorIndexRoute
  DashboardSettingArticleIndexRoute: typeof DashboardSettingArticleIndexRoute
  DashboardSettingLandingIndexRoute: typeof DashboardSettingLandingIndexRoute
  DashboardSettingTutorialIndexRoute: typeof DashboardSettingTutorialIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountSlugRoute: DashboardAccountSlugRoute,
  DashboardAccountCreateRoute: DashboardAccountCreateRoute,
  DashboardEmailIdRoute: DashboardEmailIdRoute,
  DashboardEmailCreateRoute: DashboardEmailCreateRoute,
  DashboardPlatformProductIdRoute: DashboardPlatformProductIdRoute,
  DashboardPlatformProductCreateRoute: DashboardPlatformProductCreateRoute,
  DashboardProductCreateRoute: DashboardProductCreateRoute,
  DashboardTransactionCreateRoute: DashboardTransactionCreateRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
  DashboardEmailMessageIndexRoute: DashboardEmailMessageIndexRoute,
  DashboardEmailIndexRoute: DashboardEmailIndexRoute,
  DashboardPlatformProductIndexRoute: DashboardPlatformProductIndexRoute,
  DashboardProductIndexRoute: DashboardProductIndexRoute,
  DashboardSettingIndexRoute: DashboardSettingIndexRoute,
  DashboardTransactionIndexRoute: DashboardTransactionIndexRoute,
  DashboardVoucherGeneratorIndexRoute: DashboardVoucherGeneratorIndexRoute,
  DashboardSettingArticleIndexRoute: DashboardSettingArticleIndexRoute,
  DashboardSettingLandingIndexRoute: DashboardSettingLandingIndexRoute,
  DashboardSettingTutorialIndexRoute: DashboardSettingTutorialIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
