[app]
name = "PC Gilang"
max_concurrent_tasks = 3
task_timeout_ms = 300000
api_base_url = "api.digitalpremium.id"
headless=false
# Sinkronisasi sesi via Google Drive Desktop (G:)
cloud_data_dir = "G:\\My Drive\\VolveBotData"

[api]
email = "paytronikpremium@gmail.com"
password = "@Aezakmi123"

[connector]
enabled = true

[logger]
level = "info"

# [[modules]]
# module = "shopee-order"
# name = "paytronik"
# recycle_interval = 30
# loginKey = "anangg628@gmail.com"
# password = "Jogokariyan78"
# delivery_mode = "account"
# message_before = [
# """
# RULES NTFLIX (WAJIB BACA)
# 
# 1. Hanya untuk 1 Device (ganti device tidak ada garansi)
# 2. Dilarang Mengubah/menggunakan profile yang bukan miliknya
# 3. Dilarang Mengubah Apapun (termasuk pin, nama profile dan password)
# 4. Melanggar :  GARANSI HANGUS
# """
# ]
# message_after = [
# """
# Tolong Bantu Ulasan bintang 5 ya kak :) ⭐⭐⭐⭐⭐
# 
# Untuk pembelian selanjutnya hanya Rp.5000 klik ==> s.id/LangganandiWea
# Kalo gabisa di klik copy aja terus paste ke web
# 
#     --------THANK YOU--------
# """
# ]
# message_fallback = """
# Pesanan kaka sudah kami terima dan akan kami proses segera,
# mohon ditunggu 🙏 jika dalam 10 menit tidak memberikan akun silahkan chat kewa
# klik ==> s.id/LangganandiWea Kalo gabisa di klik copy aja terus paste ke web"""

# [[modules]]
# module = "shopee-order"
# name = "volvepremium.id"
# recycle_interval = 30
# loginKey = "adnangilang13@gmail.com"
# password = "Baguvix123"
# delivery_mode = "account"
# message_before = [
# """
# ➡️ GARANSI FULL
# ➡️ Wajib install ulang aplikasi sebelum login! Untuk menghindari bug/error durasi
# ➡️ Login via Email
# ➡️ max login 1 device
# ➡️ Login pc bisa via QR, jadi loginkan dulu di hp
# ➡️ Jika terdapat kendala silahkan hubungi admin  
# """
# ]
# message_after = [
# """
# Tolong Bantu Ulasan bintang 5 ya kak :) ⭐⭐⭐⭐⭐
# 
# Klaim Free CANVA PRO 1 Bulan silahkan chat admin diWea klik ==> s.id/LangganandiWea
# Kalo gabisa di klik copy aja terus paste ke web
# 
#     --------THANK YOU--------
# """
# ]
# message_fallback = """
# Pesanan kaka sudah kami terima dan akan kami proses segera,
# mohon ditunggu 🙏 jika dalam 10 menit tidak memberikan akun silahkan chat kewa
# klik ==> s.id/LangganandiWea Kalo gabisa di klik copy aja terus paste ke web"""

# [[modules]]
# module = "shopee-order"
# name = "digital_premium"
# recycle_interval = 30
# loginKey = "digitalpremium.id"
# password = "Bintang78"
# delivery_mode = "account"
# message_before = [
# """
# RULES NTFLIX (WAJIB BACA)
# 
# 1. Hanya untuk 1 Device (ganti device tidak ada garansi)
# 2. Dilarang Mengubah/menggunakan profile yang bukan miliknya
# 3. Dilarang Mengubah Apapun (termasuk pin, nama profile dan password)
# 4. Melanggar :  GARANSI HANGUS
# """
# ]
# message_after = [
# """
# Tolong Bantu Ulasan bintang 5 ya kak :) ⭐⭐⭐⭐⭐
# 
# Untuk pembelian selanjutnya hanya Rp.5000 klik ==> s.id/LangganandiWea
# Kalo gabisa di klik copy aja terus paste ke web
# 
#     --------THANK YOU--------
# """
# ]
# message_fallback = """
# Pesanan kaka sudah kami terima dan akan kami proses segera,
# mohon ditunggu 🙏 jika dalam 10 menit tidak memberikan akun silahkan chat kewa
# klik ==> s.id/LangganandiWea Kalo gabisa di klik copy aja terus paste ke web"""

# [[modules]]
# module = "shopee-order"
# name = "papapremium"
# recycle_interval = 30
# loginKey = "papapremium"
# password = "Baguvix123"
# delivery_mode = "account"
# message_before = [
# """
# RULES NTFLIX (WAJIB BACA)
# 
# 1. Hanya untuk 1 Device (ganti device tidak ada garansi)
# 2. Dilarang Mengubah/menggunakan profile yang bukan miliknya
# 3. Dilarang Mengubah Apapun (termasuk pin, nama profile dan password)
# 4. Melanggar :  GARANSI HANGUS
# """
# ]
# message_after = [
# """
# Tolong Bantu Ulasan bintang 5 ya kak :) ⭐⭐⭐⭐⭐
# 
# Untuk pembelian selanjutnya hanya Rp.5000 klik ==> s.id/LangganandiWea
# Kalo gabisa di klik copy aja terus paste ke web
# 
#     --------THANK YOU--------
# """
# ]
# message_fallback = """
# Pesanan kaka sudah kami terima dan akan kami proses segera,
# mohon ditunggu 🙏 jika dalam 10 menit tidak memberikan akun silahkan chat kewa
# klik ==> s.id/LangganandiWea Kalo gabisa di klik copy aja terus paste ke web"""

[[modules]]
module = "netflix"
name = "netflix"

# [[modules]]
# module = "duoke"
# name = "duoke"
# loop_interval = 2000
# reply_lines = "Ready kak Silahkan Order || langsung CO aja proses cepat"
# reply_ready_to_ship = "Pesanan kakak sudah kami terima dan sedang kami proses. Mohon ditunggu sebentar ya"
# reply_unpaid = "Segara selesaikan payment dan akan kami proses secepatnya kak 😊"
# Shipped_reply_harian = "Berikut Pesanannya ya kak"
# Shipped_reply_habis_harian = "Mohon maaf kak durasinya sudah habis ya kak. Kakak order yang di etalase harian, ya? Mohon cek lagi deskripsinya, karena batas waktunya hanya 22-24 jam ya kak 🙏 || Silahkan CO lagi kak atau keWea aja lebih murah cuma 5k \n\nklik ==> s.id/LangganandiWea \nkalo gabisa diklik copy aja lalu paste di browser web"
# Shipped_reply_mingguan = "Berikut Pesanannya ya kak"
# Shipped_reply_habis_mingguan = "Mohon maaf kak durasinya sudah habis ya kak. Kakak order yang di etalase mingguan, ya? Mohon cek lagi deskripsinya, karena batas waktunya hanya 7 hari ya kak 🙏 || Silahkan CO lagi kak atau keWea aja lebih murah cuma 20k \n\nklik ==> s.id/LangganandiWea \nkalo gabisa diklik copy aja lalu paste di browser web"
# Shipped_reply_sharing_bulanan = "Berikut Pesanannya ya kak"
# Shipped_reply_habis_sharing_bulanan = "Mohon maaf kak durasinya sudah habis ya kak. Kakak order yang di etalase bulanan, ya? Mohon cek lagi deskripsinya, karena batas waktunya hanya 25-30 hari ya kak 🙏 || Silahkan CO lagi kak atau keWea aja lebih murah cuma 35k \n\nklik ==> s.id/LangganandiWea \nkalo gabisa diklik copy aja lalu paste di browser web"
# Shipped_reply_bulanan = "Berikut Pesanannya ya kak"
# Shipped_reply_habis_bulanan = "Mohon maaf kak durasinya sudah habis ya kak. Kakak order yang di etalase bulanan, ya? Mohon cek lagi deskripsinya, karena batas waktunya hanya 27-30 hari ya kak 🙏 || Silahkan CO lagi kak atau keWea aja lebih murah cuma 50k \n\nklik ==> s.id/LangganandiWea \nkalo gabisa diklik copy aja lalu paste di browser web"
