export const NETFLIX_OTP = 'NETFLIX_OTP';
export const DISNEY_OTP = 'DISNEY_OTP';
export const NETFLIX_REQ_RESET_PASSWORD = 'NETFLIX_REQ_RESET_PASSWORD';
export const NETFLIX_GENERAL_NOTIFICATION = 'NETFLIX_GENERAL_NOTIFICATION';
export const NETFLIX_HOUSE_CHANGE = 'NETFLIX_HOUSE_CHANGE';
