export const ALL_PERMISSIONS = [
  { name: 'dashboard.view', description: 'Melihat halaman dashboard utama' },
  { name: 'product.view', description: 'Melihat daftar produk' },
  { name: 'product.create', description: 'Membuat produk baru' },
  { name: 'product.edit', description: 'Mengedit produk' },
  { name: 'product.delete', description: 'Menghapus produk' },
  { name: 'user.view', description: 'Melihat daftar staff' },
  { name: 'user.create', description: 'Membuat akun staff baru' },
  { name: 'user.edit', description: 'Mengedit akun staff' },
  { name: 'user.delete', description: 'Menghapus akun staff' },
  { name: 'role.view', description: 'Melihat daftar role' },
  { name: 'role.create', description: 'Membuat role baru' },
  { name: 'role.edit', description: 'Mengedit role' },
  { name: 'role.delete', description: 'Menghapus role' },
  { name: 'transaction.view', description: 'Melihat daftar transaksi' },
  { name: 'transaction.create', description: 'Membuat transaksi' },
  { name: 'transaction.edit', description: 'Mengedit transaksi' },
  { name: 'transaction.delete', description: 'Menghapus transaksi' },
  { name: 'setting.view', description: 'Melihat pengaturan' },
  { name: 'setting.edit', description: 'Mengubah pengaturan' },
  { name: 'voucher.view', description: 'Melihat voucher' },
  { name: 'voucher.create', description: 'Membuat voucher' },
  { name: 'voucher.edit', description: 'Mengedit voucher' },
  { name: 'voucher.delete', description: 'Menghapus voucher' },
  { name: 'platform_product.view', description: 'Melihat produk dari platform' },
  { name: 'platform_product.create', description: 'Menambahkan produk platform' },
  { name: 'platform_product.edit', description: 'Mengelola produk dari platform' },
  { name: 'platform_product.delete', description: 'Menghapus produk platform' },
  { name: 'account.view', description: 'Melihat daftar akun' },
  { name: 'account.create', description: 'Membuat akun' },
  { name: 'account.edit', description: 'Mengelola akun' },
  { name: 'account.delete', description: 'Menghapus akun' },
  { name: 'email.view', description: 'Melihat inbox dan log email' },
  { name: 'email.create', description: 'Membuat email forward dan subjek' },
  { name: 'email.edit', description: 'Mengelola email forward dan subjek' },
  { name: 'email.delete', description: 'Menghapus email forward dan subjek' },
  { name: 'email_message.view', description: 'Melihat system email message' },
  { name: 'wallet.view', description: 'Melihat saldo dan mutasi wallet' },
  { name: 'wallet.create', description: 'Menambahkan bank account (wallet)' },
  { name: 'wallet.edit', description: 'Mengelola bank account (wallet)' },
  { name: 'wallet.delete', description: 'Menghapus bank account (wallet)' },
  { name: 'content.view', description: 'Melihat daftar artikel dan tutorial' },
  { name: 'content.create', description: 'Membuat artikel dan tutorial' },
  { name: 'content.edit', description: 'Mengelola artikel dan tutorial' },
  { name: 'content.delete', description: 'Menghapus artikel dan tutorial' },
  { name: 'landing.view', description: 'Melihat pengaturan landing page CMS' },
  { name: 'landing.edit', description: 'Mengelola desain dan konten landing page' },
  { name: 'withdrawal.view', description: 'Melihat pengajuan penarikan dana' },
  { name: 'withdrawal.edit', description: 'Menyetujui atau menolak penarikan dana' },
  { name: 'device.view', description: 'Melihat daftar perangkat yang terkoneksi ke tenant' },
  { name: 'device.delete', description: 'Mengeluarkan perangkat dari akun (Force Logout)' },
];

export const ROLE_PRESETS = [
  {
    name: 'Super Admin',
    description: 'Akses penuh ke semua fitur',
    permissions: ALL_PERMISSIONS.map(p => p.name),
  },
  {
    name: 'Admin',
    description: 'Akses ke semua fitur kecuali manajemen role',
    permissions: ALL_PERMISSIONS.filter(p => !p.name.startsWith('role.')).map(p => p.name),
  },
  {
    name: 'Staff CS',
    description: 'Akses dashboard dan transaksi',
    permissions: ['dashboard.view', 'transaction.view', 'transaction.create', 'voucher.view'],
  },
  {
    name: 'Viewer',
    description: 'Hanya bisa melihat data',
    permissions: ALL_PERMISSIONS.filter(p => p.name.endsWith('.view')).map(p => p.name),
  },
];
