export const NETFLIX_RESET_PASSWORD = 'NETFLIX_RESET_PASSWORD';
export const SUBS_END_NOTIFY = 'SUBS_END_NOTIFY';
export const UNFREEZE_ACCOUNT = 'UNFREEZE_ACCOUNT';
export const SUBS_END_DISABLE_ACCOUNT = 'SUBS_END_DISABLE_ACCOUNT';
