[app]
api_base_url = "https://api.volve-capital.com" # DO NOT CHANGE THIS LINE
name = "CHANGE_THIS_TO_YOUR_DESIRED_BOT_NAME"
max_concurrent_tasks = 3
task_timeout_ms = 300000
headless = false # false = headed browser, true = headless browser

[api]
app_id = "CHANGE_THIS_TO_YOUR_APP_ID"
app_secret = "CHANGE_THIS_TO_YOUR_APP_PASSWORD"

[connector]
enabled = true # DO NOT CHANGE THIS LINE

[logger]
level = "info"

# THIS IS EXAMPLE TO USE SHOPEE ORDER MODULE, CAN RUN MULTIPLE SHOPEE ORDER MODULE.
[[modules]]
module = "shopee-order"
name = "CHANGE_TO_YOUR_DESIRED_NAME_FOR_THIS_MODULE. usually same as your shopee shop name"
recycle_interval = 30
loginKey = "CHANGE_TO_YOUR_SHOPEE_LOGINKEY"
password = "CHANGE_TO_YOUR_SHOPEE_PASSWORD"
message_before = [
"""
MESSAGE TO SEND BEFORE THE ACCOUNT.

IT SUPPORT MULTILINE AND EMOJI 👍
"""
]
message_after = [
"""
MESSAGE TO SEND AFTER THE ACCOUNT.

IT SUPPORT MULTILINE AND EMOJI 👍
"""
]
message_fallback = "MESSAGE TO SEND IF THE APP ERROR AND SUPPORT EMOJI 👍"

# THIS IS EXAMPLE TO USE NETFLIX MODULE, JUST RUN 1 NETFLIX MODULE EACH BOT INSTANCE.
[[modules]]
module = "netflix"
name = "netflix"
